export default function state() {
    return {
      activeProduct: null,
        search: "",
        products: [
            { id: 1,
              name: 'Night City Cruising in GTA Vice City Definitive Edition',
              url: 'https://www.youtube.com/watch?v=RfJIhNURUc8',
              cover: 'https://i.ytimg.com/vi/RfJIhNURUc8/maxresdefault.jpg'  },
            { id: 2,
              name: 'ერისიონი',
              url: 'https://www.youtube.com/watch?v=cX5ZulcMunk&list=RDMM8qVVavw9C7U&index=2',
              cover: 'https://cdn.imedi.ge/new/V/2105/30/38/39/VURVEX1QQka5SCrp9gCxYQ/sample-20210517_230324-flv_snapshot_17-32_-2021-05-17_23-23-31.jpg'   },
            { id: 3,
              name: 'ნართები',
              url: 'https://www.youtube.com/watch?v=t2vST0nt_ns',
              cover: "https://i.ytimg.com/vi/t2vST0nt_ns/maxresdefault.jpg" },
            { id: 4, 
              name: 'სუხიშვილები',
              url: 'https://www.youtube.com/watch?v=2qNnJHNCYwY',
              cover: "https://i.ytimg.com/vi/ANwmys5SaQY/maxresdefault.jpg" },
            { id: 5, 
              name: 'Gustavo Santaolalla - Babel (Otnicka Remix)',
              url: 'https://www.youtube.com/watch?v=q7QyKLN25EY',
              cover: "https://i.ytimg.com/vi/q7QyKLN25EY/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGIgYihiMA8=&rs=AOn4CLALFbhEhoh_QockAtXLfRt2Y25j7A" },
            { id: 6, 
              name: 'Naruto Shippuden - Tragic (Anigam3 Remix) [SM Release]',
              url: 'https://www.youtube.com/watch?v=oabl6jc0xJo&list=RDMM&start_radio=1&rv=q7QyKLN25EY',
              cover: "https://i.ytimg.com/vi/oabl6jc0xJo/maxresdefault.jpg" },
            { id: 7, 
              name: 'Goku Vs. Jiren「AMV」- Get Me Out',
              url: 'https://www.youtube.com/watch?v=OSyKhqDsW14',
              cover: "https://i.ytimg.com/vi/OSyKhqDsW14/maxresdefault.jpg" },
            { id: 8, 
              name: 'Naruto Saddest Soundtracks Mix',
              url: 'https://www.youtube.com/watch?v=YR7dyQa-8q0',
              cover: "https://i.ytimg.com/vi/YR7dyQa-8q0/maxresdefault.jpg" },
            { id: 9, 
              name: 'Gazapizm - Kalbim Çukurda ft. Cem Adrian',
              url: 'https://www.youtube.com/watch?v=pug7nqLd8u4',
              cover: "https://i.ytimg.com/vi/pug7nqLd8u4/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgZShlMA8=&rs=AOn4CLBT6YTz7sC-TS6hXBE508jonaWeWA" },
           {  id: 10, 
              name: 'West Side 2Pac, Pop Smoke, Biggie, DMX, Eazy E, Ice Cube, Dr Dre, NWA, Nipsey, Snoop Dogg',
              url: 'https://www.youtube.com/watch?v=qAZw1V3LyZE',
              cover: "https://i.ytimg.com/vi/Oi-C2npBCYI/maxresdefault.jpg" },
           {  id: 11, 
              name: 'The Lord of the Rings: The Fellowship of the Ring FuLLMovie HD',
              url: 'https://www.youtube.com/watch?v=nD4HmPbweNI',
              cover: "https://uk.imageservice.sky.com/pcms/54a43326-d0cd-11ea-a8ec-0bf436b2a4fe/16_9" },
           {  id: 12, 
              name: 'Naruto ( Kakashi Hatake)',
              url: 'https://www.youtube.com/watch?v=XAwU7x1w1Ts',
              cover: "https://i.ytimg.com/vi/XAwU7x1w1Ts/maxresdefault.jpg" },
          {   id: 13, 
              name: 'Jariko-U (Original Mix)',
              url: 'https://www.youtube.com/watch?v=w7FxXzCty90',
              cover: "https://i.ytimg.com/vi/qdNf0YXpyhY/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgZShlMA8=&rs=AOn4CLAO4mSD66-0uRkjxJLoJcua0fpZqQ" },
          {   id: 14, 
              name: 'GTA სან ანდრეასი - განხილვა',
              url: 'https://www.youtube.com/watch?v=_rpCebBpjnY&t=407s',
              cover: "https://i.ytimg.com/vi/_rpCebBpjnY/maxresdefault.jpg" },
          {   id: 15, 
              name: 'Gta Vice City - განხილვა',
              url: 'https://www.youtube.com/watch?v=jXMnHGpo2wk',
              cover: "https://i.ytimg.com/vi/jXMnHGpo2wk/maxresdefault.jpg" },
          {   id: 16, 
              name: 'Miyagi- Kolibri',
              url: 'https://www.youtube.com/watch?v=pz2Ixqni3_k',
              cover: "https://i.ytimg.com/vi/pz2Ixqni3_k/maxresdefault.jpg" },


        ],
        cart: []
    }
}